name: Release

on:
  push:
    tags:
      - 'v*'  # Ausgelöst bei Tag Push, z.B. v1.0.0

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]  # Matrix für Linux + Windows

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm install

      # 4️⃣ package
      - name: package
        run: npx package

      # 5️⃣ Determine the output file (tar.gz for Linux, zip for Windows)
      - name: set artifact on linux
        if: matrix.os == 'ubuntu-latest'
        #id: artifact
        run: |
          echo "artifact_path=../ts-fix-videos.tar.gz" >> $GITHUB_ENV
          echo "artifact_name=ts-fix-videos-linux.tar.gz" >> $GITHUB_ENV

      - name: Set artifact on windows
        if: matrix.os == 'windows-latest'
        #id: artifact
        run: |
          echo "artifact_path=..\ts-fix-videos.zip" >> $GITHUB_ENV
          echo "artifact_name=ts-fix-videos-windows.zip" >> $GITHUB_ENV

      # 6️⃣ Create GitHub Release
      - name: Create GitHub Release
        if: matrix.os == 'ubuntu-latest'
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 7️⃣ Upload Release Asset
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        if: matrix.os == 'ubuntu-latest'
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.artifact_path }}
          asset_name: ${{ env.artifact_name }}
          asset_content_type: application/octet-stream